services:
  pokedex-app:
    container_name: pokedex-app
    build:
      context: .
      dockerfile: ./packages/pokedex-app/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - local

networks:
  local:

