version: '3'

services:
  pokedex-redux:
    container_name: pokedex-redux
    build:
      context: .
      dockerfile: ./packages/pokedex-app/Dockerfile
      args:
        NODE_ENV: production
        NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL
    ports:
      - 3000:3000
    networks:
      - local
    volumes:

networks:
  local:

