version: "3"

services:
  pokedex-app:
    container_name: pokedex-app
    build:
      context: .
      dockerfile: ./packages/pokedex-app/Dockerfile
      args:
        NODE_ENV: production
        NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL
    ports:
      - 3000:3000
    networks:
      - local

networks:
  local:
